// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9z3zhiUZ6LvKjAngsfCRXrMwG4ffz8Es',
    appId: '1:981335290628:web:664712e473f360422c5651',
    messagingSenderId: '981335290628',
    projectId: 'clickfare-37fe5',
    authDomain: 'clickfare-37fe5.firebaseapp.com',
    storageBucket: 'clickfare-37fe5.appspot.com',
    measurementId: 'G-TSWRLGMM0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlPTOCjhMhBtqF9NTmYxAzQx1FW_WvIuY',
    appId: '1:981335290628:android:eeb470625d4981312c5651',
    messagingSenderId: '981335290628',
    projectId: 'clickfare-37fe5',
    storageBucket: 'clickfare-37fe5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH4If5W9LpJTIAkgrJ5zbndBGQ6VRolLk',
    appId: '1:981335290628:ios:fe2fd616346532b82c5651',
    messagingSenderId: '981335290628',
    projectId: 'clickfare-37fe5',
    storageBucket: 'clickfare-37fe5.appspot.com',
    iosBundleId: 'com.example.clickFare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH4If5W9LpJTIAkgrJ5zbndBGQ6VRolLk',
    appId: '1:981335290628:ios:afe4101ce3673f852c5651',
    messagingSenderId: '981335290628',
    projectId: 'clickfare-37fe5',
    storageBucket: 'clickfare-37fe5.appspot.com',
    iosBundleId: 'com.example.clickFare.RunnerTests',
  );
}
